### ISSUE TITLE
flac thumbnails not showing in Dophin

### ISSUE THREAD

**Issue by doubletimedan** [saltedcoffii/ffmpeg-audio-thumbnailer#2]
I am not sure if this tool is to create thumbnails or if it is just to show them but either way my flac songs do not show their images on dolphin, If you need any more info just ask

Os: Archlinux
Dolphin version: 22.08.1

![Screenshot_20220929_141628_v1](https://user-images.githubusercontent.com/65255420/193045636-6862f70e-f389-41ad-8ee7-60c9f57cab7d.png)
![Screenshot_20220929_143308](https://user-images.githubusercontent.com/65255420/193045643-ee370bde-4bc5-44aa-b6aa-675160a6b580.png)

**Comment by doubletimedan** [comment]
almost forgot, I am on version 1.1.0 of ffmpeg-audio-thumbnailer

**Comment by saltedcoffii** [comment]
Hmm, let me look into this. Are you getting any thumbnails from this package at all? Do you have mp3 files with a thumbnail?

Also, could you try running `rm -rf ~/.thumbnails ~/.cache/thumbnails` to clear the thumbnail cache and then restart dolphin? If neither of those work, get back to me and I'll look into it.

Are you using Arch Linux's official ffmpeg version, or a version from the AUR? Would you mind running `ffmpeg -codecs 2> /dev/null | grep flac` and make sure the line `DEAI.S flac         FLAC (Free Lossless Audio Codec)` shows up?

**Comment by doubletimedan** [comment]
- ok so I checked some mp3 files with thumbnails and they do in fact show their thumbnails, idk how to check if they are coming from this package though
- I ran rm -rf ~/.thumbnails ~/.cache/thumbnails, then restarted dolphin and nothing changed
- I ran ffmpeg -codecs 2> /dev/null | grep flac and it does show DEAI.S flac                 FLAC (Free Lossless Audio Codec)

![Screenshot_20220929_163638](https://user-images.githubusercontent.com/65255420/193075870-b44658d5-283c-4282-9583-955e778d52b2.png)

**Comment by saltedcoffii** [comment]
would you mind emailing me one of the flac files you're using

**Comment by doubletimedan** [comment]
What's your email?

**Comment by saltedcoffii** [comment]
Oh i put <> around it and i guess that made it disappear, it's "cassandrajwatergate AT gmail DOT com"

**Comment by doubletimedan** [comment]
No problem, I just sent you an email

**Comment by saltedcoffii** [comment]
The flac file that you sent me is thumbnailing just fine for me on nautilus and dolphin. I don't think whatever issue you're having is with `ffmpeg-audio-thumbnailer`. I'd love to help you debug, but this is the limit of my knowledge of how thumbnailers work, unfortunately.

**Comment by saltedcoffii** [comment]
Could you send me your `/usr/share/thumbnailers` directory to see if there might be any conflicts or issues there? If you aren't sure how to do that, you can `cd` into and writable directory (`~/Downloads` is fine) run:
```
cp -r /usr/share/thumbnailers .
tar -cvf doubletimedans-thumbnailers.tar thumbnailers
zstd -T0 --ultra -22 --rm doubletimedans-thumbnailers.tar
rm -r thumbnailers
```
And then just send me `doubletimedans-thumbnailers.tar.zst`

**Comment by doubletimedan** [comment]
alright I have just sent you an email with that folder

**Comment by saltedcoffii** [comment]
I'm sorry, I don't know. If you figure it out, let me know.

**Comment by doubletimedan** [comment]
Alright np I will, can you send me the file you get when you run "pacman -Q > flac_thumbnail.txt" I probably don't have a package that I need for it to show or something

**Comment by saltedcoffii** [comment]
[flac_thumbnail.txt](https://github.com/saltedcoffii/ffmpeg-audio-thumbnailer/files/10089990/flac_thumbnail.txt)

Sorry that took me so long @doubletimedan 
Please let me know if you figure out what the problem is

**Comment by doubletimedan** [comment]
No luck, I have to switch back to windows for a while to do an important project so I will not be able to test it on Linux again but I can say the thumbnails do show up now on windows and if it shows up for you then it was probably my fault somehow so I'm going to close the issue as it's nothing got to do with your package, thank you for all the help anyways!
