### ISSUE TITLE
Possible neccessity of ffmpeg -y flag?

### ISSUE THREAD

**Issue by pancaek** [saltedcoffii/ffmpeg-audio-thumbnailer#4]
When using  EasyTAG to manually tag audio files with covers, the thumbnails aren't applied at all unless I modify the thumbnailer file to use ffmpeg's -y flag to allow overwriting the output files. 

This remains the case even when manually removing the thumbnail cache from `.cache/thumbnails` to force a rebuild, as well as if I try restarting tumblerd. 

After adding the -y flag, EasyTAG thumbnails are successfully recognized, and additionally update as soon as they are saved in EasyTAG.

**Comment by pancaek** [comment]
I'd be happy to write the (admittedly very tiny) PR for this, but I thought it best to first raise the issue in case it is not reproducible/not worth implementing for some other reason.

**Comment by saltedcoffii** [comment]
I'm not familiar with easytag software but would be happy to see a pr for compatibility

**Comment by pancaek** [comment]
Awesome, I just made the PR

**Comment by saltedcoffii** [comment]
Fixed #5
